
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point valid_in valid_in -type PI PI
add mapped point a[31] a[31] -type PI PI
add mapped point a[30] a[30] -type PI PI
add mapped point a[29] a[29] -type PI PI
add mapped point a[28] a[28] -type PI PI
add mapped point a[27] a[27] -type PI PI
add mapped point a[26] a[26] -type PI PI
add mapped point a[25] a[25] -type PI PI
add mapped point a[24] a[24] -type PI PI
add mapped point a[23] a[23] -type PI PI
add mapped point a[22] a[22] -type PI PI
add mapped point a[21] a[21] -type PI PI
add mapped point a[20] a[20] -type PI PI
add mapped point a[19] a[19] -type PI PI
add mapped point a[18] a[18] -type PI PI
add mapped point a[17] a[17] -type PI PI
add mapped point a[16] a[16] -type PI PI
add mapped point a[15] a[15] -type PI PI
add mapped point a[14] a[14] -type PI PI
add mapped point a[13] a[13] -type PI PI
add mapped point a[12] a[12] -type PI PI
add mapped point a[11] a[11] -type PI PI
add mapped point a[10] a[10] -type PI PI
add mapped point a[9] a[9] -type PI PI
add mapped point a[8] a[8] -type PI PI
add mapped point a[7] a[7] -type PI PI
add mapped point a[6] a[6] -type PI PI
add mapped point a[5] a[5] -type PI PI
add mapped point a[4] a[4] -type PI PI
add mapped point a[3] a[3] -type PI PI
add mapped point a[2] a[2] -type PI PI
add mapped point a[1] a[1] -type PI PI
add mapped point a[0] a[0] -type PI PI
add mapped point b[31] b[31] -type PI PI
add mapped point b[30] b[30] -type PI PI
add mapped point b[29] b[29] -type PI PI
add mapped point b[28] b[28] -type PI PI
add mapped point b[27] b[27] -type PI PI
add mapped point b[26] b[26] -type PI PI
add mapped point b[25] b[25] -type PI PI
add mapped point b[24] b[24] -type PI PI
add mapped point b[23] b[23] -type PI PI
add mapped point b[22] b[22] -type PI PI
add mapped point b[21] b[21] -type PI PI
add mapped point b[20] b[20] -type PI PI
add mapped point b[19] b[19] -type PI PI
add mapped point b[18] b[18] -type PI PI
add mapped point b[17] b[17] -type PI PI
add mapped point b[16] b[16] -type PI PI
add mapped point b[15] b[15] -type PI PI
add mapped point b[14] b[14] -type PI PI
add mapped point b[13] b[13] -type PI PI
add mapped point b[12] b[12] -type PI PI
add mapped point b[11] b[11] -type PI PI
add mapped point b[10] b[10] -type PI PI
add mapped point b[9] b[9] -type PI PI
add mapped point b[8] b[8] -type PI PI
add mapped point b[7] b[7] -type PI PI
add mapped point b[6] b[6] -type PI PI
add mapped point b[5] b[5] -type PI PI
add mapped point b[4] b[4] -type PI PI
add mapped point b[3] b[3] -type PI PI
add mapped point b[2] b[2] -type PI PI
add mapped point b[1] b[1] -type PI PI
add mapped point b[0] b[0] -type PI PI

//output ports
add mapped point valid_out valid_out -type PO PO
add mapped point product[63] product[63] -type PO PO
add mapped point product[62] product[62] -type PO PO
add mapped point product[61] product[61] -type PO PO
add mapped point product[60] product[60] -type PO PO
add mapped point product[59] product[59] -type PO PO
add mapped point product[58] product[58] -type PO PO
add mapped point product[57] product[57] -type PO PO
add mapped point product[56] product[56] -type PO PO
add mapped point product[55] product[55] -type PO PO
add mapped point product[54] product[54] -type PO PO
add mapped point product[53] product[53] -type PO PO
add mapped point product[52] product[52] -type PO PO
add mapped point product[51] product[51] -type PO PO
add mapped point product[50] product[50] -type PO PO
add mapped point product[49] product[49] -type PO PO
add mapped point product[48] product[48] -type PO PO
add mapped point product[47] product[47] -type PO PO
add mapped point product[46] product[46] -type PO PO
add mapped point product[45] product[45] -type PO PO
add mapped point product[44] product[44] -type PO PO
add mapped point product[43] product[43] -type PO PO
add mapped point product[42] product[42] -type PO PO
add mapped point product[41] product[41] -type PO PO
add mapped point product[40] product[40] -type PO PO
add mapped point product[39] product[39] -type PO PO
add mapped point product[38] product[38] -type PO PO
add mapped point product[37] product[37] -type PO PO
add mapped point product[36] product[36] -type PO PO
add mapped point product[35] product[35] -type PO PO
add mapped point product[34] product[34] -type PO PO
add mapped point product[33] product[33] -type PO PO
add mapped point product[32] product[32] -type PO PO
add mapped point product[31] product[31] -type PO PO
add mapped point product[30] product[30] -type PO PO
add mapped point product[29] product[29] -type PO PO
add mapped point product[28] product[28] -type PO PO
add mapped point product[27] product[27] -type PO PO
add mapped point product[26] product[26] -type PO PO
add mapped point product[25] product[25] -type PO PO
add mapped point product[24] product[24] -type PO PO
add mapped point product[23] product[23] -type PO PO
add mapped point product[22] product[22] -type PO PO
add mapped point product[21] product[21] -type PO PO
add mapped point product[20] product[20] -type PO PO
add mapped point product[19] product[19] -type PO PO
add mapped point product[18] product[18] -type PO PO
add mapped point product[17] product[17] -type PO PO
add mapped point product[16] product[16] -type PO PO
add mapped point product[15] product[15] -type PO PO
add mapped point product[14] product[14] -type PO PO
add mapped point product[13] product[13] -type PO PO
add mapped point product[12] product[12] -type PO PO
add mapped point product[11] product[11] -type PO PO
add mapped point product[10] product[10] -type PO PO
add mapped point product[9] product[9] -type PO PO
add mapped point product[8] product[8] -type PO PO
add mapped point product[7] product[7] -type PO PO
add mapped point product[6] product[6] -type PO PO
add mapped point product[5] product[5] -type PO PO
add mapped point product[4] product[4] -type PO PO
add mapped point product[3] product[3] -type PO PO
add mapped point product[2] product[2] -type PO PO
add mapped point product[1] product[1] -type PO PO
add mapped point product[0] product[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point product[46]/q product_reg[46]/Q  -type DFF DFF
add mapped point product[63]/q product_reg[63]/Q  -type DFF DFF
add mapped point product[61]/q product_reg[61]/Q  -type DFF DFF
add mapped point product[57]/q product_reg[57]/Q  -type DFF DFF
add mapped point product[49]/q product_reg[49]/Q  -type DFF DFF
add mapped point product[33]/q product_reg[33]/Q  -type DFF DFF
add mapped point product[32]/q product_reg[32]/Q  -type DFF DFF
add mapped point product[48]/q product_reg[48]/Q  -type DFF DFF
add mapped point product[31]/q product_reg[31]/Q  -type DFF DFF
add mapped point product[30]/q product_reg[30]/Q  -type DFF DFF
add mapped point product[56]/q product_reg[56]/Q  -type DFF DFF
add mapped point product[47]/q product_reg[47]/Q  -type DFF DFF
add mapped point product[29]/q product_reg[29]/Q  -type DFF DFF
add mapped point product[28]/q product_reg[28]/Q  -type DFF DFF
add mapped point product[27]/q product_reg[27]/Q  -type DFF DFF
add mapped point product[26]/q product_reg[26]/Q  -type DFF DFF
add mapped point product[60]/q product_reg[60]/Q  -type DFF DFF
add mapped point product[55]/q product_reg[55]/Q  -type DFF DFF
add mapped point product[45]/q product_reg[45]/Q  -type DFF DFF
add mapped point product[25]/q product_reg[25]/Q  -type DFF DFF
add mapped point product[24]/q product_reg[24]/Q  -type DFF DFF
add mapped point product[44]/q product_reg[44]/Q  -type DFF DFF
add mapped point product[23]/q product_reg[23]/Q  -type DFF DFF
add mapped point product[22]/q product_reg[22]/Q  -type DFF DFF
add mapped point product[54]/q product_reg[54]/Q  -type DFF DFF
add mapped point product[43]/q product_reg[43]/Q  -type DFF DFF
add mapped point product[21]/q product_reg[21]/Q  -type DFF DFF
add mapped point product[20]/q product_reg[20]/Q  -type DFF DFF
add mapped point product[42]/q product_reg[42]/Q  -type DFF DFF
add mapped point product[18]/q product_reg[18]/Q  -type DFF DFF
add mapped point product[62]/q product_reg[62]/Q  -type DFF DFF
add mapped point product[59]/q product_reg[59]/Q  -type DFF DFF
add mapped point product[53]/q product_reg[53]/Q  -type DFF DFF
add mapped point product[41]/q product_reg[41]/Q  -type DFF DFF
add mapped point product[17]/q product_reg[17]/Q  -type DFF DFF
add mapped point product[16]/q product_reg[16]/Q  -type DFF DFF
add mapped point product[40]/q product_reg[40]/Q  -type DFF DFF
add mapped point product[52]/q product_reg[52]/Q  -type DFF DFF
add mapped point product[39]/q product_reg[39]/Q  -type DFF DFF
add mapped point product[38]/q product_reg[38]/Q  -type DFF DFF
add mapped point product[19]/q product_reg[19]/Q  -type DFF DFF
add mapped point product[58]/q product_reg[58]/Q  -type DFF DFF
add mapped point product[51]/q product_reg[51]/Q  -type DFF DFF
add mapped point product[37]/q product_reg[37]/Q  -type DFF DFF
add mapped point product[36]/q product_reg[36]/Q  -type DFF DFF
add mapped point product[50]/q product_reg[50]/Q  -type DFF DFF
add mapped point product[35]/q product_reg[35]/Q  -type DFF DFF
add mapped point product[34]/q product_reg[34]/Q  -type DFF DFF
add mapped point product[15]/q product_reg[15]/Q  -type DFF DFF
add mapped point product[14]/q product_reg[14]/Q  -type DFF DFF
add mapped point product[11]/q product_reg[11]/Q  -type DFF DFF
add mapped point product[13]/q product_reg[13]/Q  -type DFF DFF
add mapped point product[9]/q product_reg[9]/Q  -type DFF DFF
add mapped point product[10]/q product_reg[10]/Q  -type DFF DFF
add mapped point product[12]/q product_reg[12]/Q  -type DFF DFF
add mapped point product[8]/q product_reg[8]/Q  -type DFF DFF
add mapped point psum_lo_s2[36]/q psum_lo_s2_reg[36]/Q  -type DFF DFF
add mapped point psum_lo_s2[9]/q psum_lo_s2_reg[9]/Q  -type DFF DFF
add mapped point psum_lo_s2[10]/q psum_lo_s2_reg[10]/Q  -type DFF DFF
add mapped point psum_lo_s2[12]/q psum_lo_s2_reg[12]/Q  -type DFF DFF
add mapped point psum_lo_s2[11]/q psum_lo_s2_reg[11]/Q  -type DFF DFF
add mapped point psum_lo_s2[13]/q psum_lo_s2_reg[13]/Q  -type DFF DFF
add mapped point psum_lo_s2[15]/q psum_lo_s2_reg[15]/Q  -type DFF DFF
add mapped point psum_lo_s2[14]/q psum_lo_s2_reg[14]/Q  -type DFF DFF
add mapped point psum_lo_s2[28]/q psum_lo_s2_reg[28]/Q  -type DFF DFF
add mapped point psum_lo_s2[47]/q psum_lo_s2_reg[47]/Q  -type DFF DFF
add mapped point psum_lo_s2[46]/q psum_lo_s2_reg[46]/Q  -type DFF DFF
add mapped point psum_lo_s2[45]/q psum_lo_s2_reg[45]/Q  -type DFF DFF
add mapped point psum_lo_s2[44]/q psum_lo_s2_reg[44]/Q  -type DFF DFF
add mapped point psum_lo_s2[43]/q psum_lo_s2_reg[43]/Q  -type DFF DFF
add mapped point psum_lo_s2[42]/q psum_lo_s2_reg[42]/Q  -type DFF DFF
add mapped point psum_lo_s2[41]/q psum_lo_s2_reg[41]/Q  -type DFF DFF
add mapped point psum_lo_s2[40]/q psum_lo_s2_reg[40]/Q  -type DFF DFF
add mapped point psum_lo_s2[39]/q psum_lo_s2_reg[39]/Q  -type DFF DFF
add mapped point psum_lo_s2[38]/q psum_lo_s2_reg[38]/Q  -type DFF DFF
add mapped point psum_lo_s2[37]/q psum_lo_s2_reg[37]/Q  -type DFF DFF
add mapped point psum_lo_s2[8]/q psum_lo_s2_reg[8]/Q  -type DFF DFF
add mapped point psum_lo_s2[35]/q psum_lo_s2_reg[35]/Q  -type DFF DFF
add mapped point psum_lo_s2[34]/q psum_lo_s2_reg[34]/Q  -type DFF DFF
add mapped point psum_lo_s2[33]/q psum_lo_s2_reg[33]/Q  -type DFF DFF
add mapped point psum_lo_s2[32]/q psum_lo_s2_reg[32]/Q  -type DFF DFF
add mapped point psum_lo_s2[31]/q psum_lo_s2_reg[31]/Q  -type DFF DFF
add mapped point psum_lo_s2[30]/q psum_lo_s2_reg[30]/Q  -type DFF DFF
add mapped point psum_lo_s2[29]/q psum_lo_s2_reg[29]/Q  -type DFF DFF
add mapped point psum_lo_s2[48]/q psum_lo_s2_reg[48]/Q  -type DFF DFF
add mapped point psum_lo_s2[27]/q psum_lo_s2_reg[27]/Q  -type DFF DFF
add mapped point psum_lo_s2[26]/q psum_lo_s2_reg[26]/Q  -type DFF DFF
add mapped point psum_lo_s2[25]/q psum_lo_s2_reg[25]/Q  -type DFF DFF
add mapped point psum_lo_s2[24]/q psum_lo_s2_reg[24]/Q  -type DFF DFF
add mapped point psum_lo_s2[23]/q psum_lo_s2_reg[23]/Q  -type DFF DFF
add mapped point psum_lo_s2[22]/q psum_lo_s2_reg[22]/Q  -type DFF DFF
add mapped point psum_lo_s2[21]/q psum_lo_s2_reg[21]/Q  -type DFF DFF
add mapped point psum_lo_s2[20]/q psum_lo_s2_reg[20]/Q  -type DFF DFF
add mapped point psum_lo_s2[19]/q psum_lo_s2_reg[19]/Q  -type DFF DFF
add mapped point psum_lo_s2[18]/q psum_lo_s2_reg[18]/Q  -type DFF DFF
add mapped point psum_lo_s2[17]/q psum_lo_s2_reg[17]/Q  -type DFF DFF
add mapped point psum_lo_s2[16]/q psum_lo_s2_reg[16]/Q  -type DFF DFF
add mapped point psum_hi_s2[47]/q psum_hi_s2_reg[47]/Q  -type DFF DFF
add mapped point psum_hi_s2[46]/q psum_hi_s2_reg[46]/Q  -type DFF DFF
add mapped point psum_hi_s2[45]/q psum_hi_s2_reg[45]/Q  -type DFF DFF
add mapped point psum_hi_s2[44]/q psum_hi_s2_reg[44]/Q  -type DFF DFF
add mapped point psum_hi_s2[43]/q psum_hi_s2_reg[43]/Q  -type DFF DFF
add mapped point psum_hi_s2[42]/q psum_hi_s2_reg[42]/Q  -type DFF DFF
add mapped point psum_hi_s2[41]/q psum_hi_s2_reg[41]/Q  -type DFF DFF
add mapped point psum_hi_s2[40]/q psum_hi_s2_reg[40]/Q  -type DFF DFF
add mapped point psum_hi_s2[39]/q psum_hi_s2_reg[39]/Q  -type DFF DFF
add mapped point psum_hi_s2[38]/q psum_hi_s2_reg[38]/Q  -type DFF DFF
add mapped point psum_hi_s2[37]/q psum_hi_s2_reg[37]/Q  -type DFF DFF
add mapped point psum_hi_s2[36]/q psum_hi_s2_reg[36]/Q  -type DFF DFF
add mapped point psum_hi_s2[35]/q psum_hi_s2_reg[35]/Q  -type DFF DFF
add mapped point psum_hi_s2[34]/q psum_hi_s2_reg[34]/Q  -type DFF DFF
add mapped point psum_hi_s2[33]/q psum_hi_s2_reg[33]/Q  -type DFF DFF
add mapped point psum_hi_s2[32]/q psum_hi_s2_reg[32]/Q  -type DFF DFF
add mapped point psum_hi_s2[31]/q psum_hi_s2_reg[31]/Q  -type DFF DFF
add mapped point psum_hi_s2[30]/q psum_hi_s2_reg[30]/Q  -type DFF DFF
add mapped point psum_hi_s2[9]/q psum_hi_s2_reg[9]/Q  -type DFF DFF
add mapped point psum_hi_s2[29]/q psum_hi_s2_reg[29]/Q  -type DFF DFF
add mapped point psum_hi_s2[28]/q psum_hi_s2_reg[28]/Q  -type DFF DFF
add mapped point psum_hi_s2[27]/q psum_hi_s2_reg[27]/Q  -type DFF DFF
add mapped point psum_hi_s2[13]/q psum_hi_s2_reg[13]/Q  -type DFF DFF
add mapped point psum_hi_s2[26]/q psum_hi_s2_reg[26]/Q  -type DFF DFF
add mapped point psum_hi_s2[25]/q psum_hi_s2_reg[25]/Q  -type DFF DFF
add mapped point psum_hi_s2[24]/q psum_hi_s2_reg[24]/Q  -type DFF DFF
add mapped point psum_hi_s2[23]/q psum_hi_s2_reg[23]/Q  -type DFF DFF
add mapped point psum_hi_s2[22]/q psum_hi_s2_reg[22]/Q  -type DFF DFF
add mapped point psum_hi_s2[21]/q psum_hi_s2_reg[21]/Q  -type DFF DFF
add mapped point psum_hi_s2[20]/q psum_hi_s2_reg[20]/Q  -type DFF DFF
add mapped point psum_hi_s2[19]/q psum_hi_s2_reg[19]/Q  -type DFF DFF
add mapped point psum_hi_s2[18]/q psum_hi_s2_reg[18]/Q  -type DFF DFF
add mapped point psum_hi_s2[17]/q psum_hi_s2_reg[17]/Q  -type DFF DFF
add mapped point psum_hi_s2[16]/q psum_hi_s2_reg[16]/Q  -type DFF DFF
add mapped point psum_hi_s2[15]/q psum_hi_s2_reg[15]/Q  -type DFF DFF
add mapped point psum_hi_s2[14]/q psum_hi_s2_reg[14]/Q  -type DFF DFF
add mapped point psum_hi_s2[12]/q psum_hi_s2_reg[12]/Q  -type DFF DFF
add mapped point psum_hi_s2[11]/q psum_hi_s2_reg[11]/Q  -type DFF DFF
add mapped point psum_hi_s2[10]/q psum_hi_s2_reg[10]/Q  -type DFF DFF
add mapped point psum_hi_s2[8]/q psum_hi_s2_reg[8]/Q  -type DFF DFF
add mapped point product[7]/q product_reg[7]/Q  -type DFF DFF
add mapped point product[0]/q product_reg[0]/Q  -type DFF DFF
add mapped point product[1]/q product_reg[1]/Q  -type DFF DFF
add mapped point product[6]/q product_reg[6]/Q  -type DFF DFF
add mapped point product[3]/q product_reg[3]/Q  -type DFF DFF
add mapped point product[4]/q product_reg[4]/Q  -type DFF DFF
add mapped point product[5]/q product_reg[5]/Q  -type DFF DFF
add mapped point product[2]/q product_reg[2]/Q  -type DFF DFF
add mapped point psum_lo_s2[2]/q psum_lo_s2_reg[2]/Q  -type DFF DFF
add mapped point psum_lo_s2[3]/q psum_lo_s2_reg[3]/Q  -type DFF DFF
add mapped point psum_lo_s2[0]/q psum_lo_s2_reg[0]/Q  -type DFF DFF
add mapped point psum_lo_s2[1]/q psum_lo_s2_reg[1]/Q  -type DFF DFF
add mapped point psum_lo_s2[7]/q psum_lo_s2_reg[7]/Q  -type DFF DFF
add mapped point psum_lo_s2[4]/q psum_lo_s2_reg[4]/Q  -type DFF DFF
add mapped point psum_lo_s2[5]/q psum_lo_s2_reg[5]/Q  -type DFF DFF
add mapped point psum_lo_s2[6]/q psum_lo_s2_reg[6]/Q  -type DFF DFF
add mapped point psum_hi_s2[4]/q psum_hi_s2_reg[4]/Q  -type DFF DFF
add mapped point psum_hi_s2[5]/q psum_hi_s2_reg[5]/Q  -type DFF DFF
add mapped point psum_hi_s2[7]/q psum_hi_s2_reg[7]/Q  -type DFF DFF
add mapped point psum_hi_s2[6]/q psum_hi_s2_reg[6]/Q  -type DFF DFF
add mapped point psum_hi_s2[1]/q psum_hi_s2_reg[1]/Q  -type DFF DFF
add mapped point psum_hi_s2[3]/q psum_hi_s2_reg[3]/Q  -type DFF DFF
add mapped point psum_hi_s2[2]/q psum_hi_s2_reg[2]/Q  -type DFF DFF
add mapped point psum_hi_s2[0]/q psum_hi_s2_reg[0]/Q  -type DFF DFF
add mapped point pp3_s1[19]/q pp3_s1_reg[19]/Q  -type DFF DFF
add mapped point pp3_s1[11]/q pp3_s1_reg[11]/Q  -type DFF DFF
add mapped point pp3_s1[7]/q pp3_s1_reg[7]/Q  -type DFF DFF
add mapped point pp3_s1[31]/q pp3_s1_reg[31]/Q  -type DFF DFF
add mapped point pp0_s1[4]/q pp0_s1_reg[4]/Q  -type DFF DFF
add mapped point pp0_s1[1]/q pp0_s1_reg[1]/Q  -type DFF DFF
add mapped point pp0_s1[2]/q pp0_s1_reg[2]/Q  -type DFF DFF
add mapped point pp0_s1[3]/q pp0_s1_reg[3]/Q  -type DFF DFF
add mapped point pp0_s1[0]/q pp0_s1_reg[0]/Q  -type DFF DFF
add mapped point pp0_s1[5]/q pp0_s1_reg[5]/Q  -type DFF DFF
add mapped point pp0_s1[6]/q pp0_s1_reg[6]/Q  -type DFF DFF
add mapped point pp0_s1[7]/q pp0_s1_reg[7]/Q  -type DFF DFF
add mapped point pp2_s1[1]/q pp2_s1_reg[1]/Q  -type DFF DFF
add mapped point pp2_s1[2]/q pp2_s1_reg[2]/Q  -type DFF DFF
add mapped point pp2_s1[4]/q pp2_s1_reg[4]/Q  -type DFF DFF
add mapped point pp2_s1[5]/q pp2_s1_reg[5]/Q  -type DFF DFF
add mapped point pp2_s1[6]/q pp2_s1_reg[6]/Q  -type DFF DFF
add mapped point pp2_s1[7]/q pp2_s1_reg[7]/Q  -type DFF DFF
add mapped point pp2_s1[3]/q pp2_s1_reg[3]/Q  -type DFF DFF
add mapped point pp2_s1[0]/q pp2_s1_reg[0]/Q  -type DFF DFF
add mapped point pp1_s1[35]/q pp1_s1_reg[35]/Q  -type DFF DFF
add mapped point pp3_s1[38]/q pp3_s1_reg[38]/Q  -type DFF DFF
add mapped point pp3_s1[27]/q pp3_s1_reg[27]/Q  -type DFF DFF
add mapped point pp3_s1[3]/q pp3_s1_reg[3]/Q  -type DFF DFF
add mapped point pp0_s1[13]/q pp0_s1_reg[13]/Q  -type DFF DFF
add mapped point pp2_s1[28]/q pp2_s1_reg[28]/Q  -type DFF DFF
add mapped point pp1_s1[24]/q pp1_s1_reg[24]/Q  -type DFF DFF
add mapped point pp2_s1[8]/q pp2_s1_reg[8]/Q  -type DFF DFF
add mapped point pp0_s1[34]/q pp0_s1_reg[34]/Q  -type DFF DFF
add mapped point pp2_s1[13]/q pp2_s1_reg[13]/Q  -type DFF DFF
add mapped point pp2_s1[15]/q pp2_s1_reg[15]/Q  -type DFF DFF
add mapped point pp2_s1[18]/q pp2_s1_reg[18]/Q  -type DFF DFF
add mapped point pp2_s1[21]/q pp2_s1_reg[21]/Q  -type DFF DFF
add mapped point pp2_s1[24]/q pp2_s1_reg[24]/Q  -type DFF DFF
add mapped point pp1_s1[28]/q pp1_s1_reg[28]/Q  -type DFF DFF
add mapped point pp3_s1[21]/q pp3_s1_reg[21]/Q  -type DFF DFF
add mapped point pp2_s1[29]/q pp2_s1_reg[29]/Q  -type DFF DFF
add mapped point pp2_s1[27]/q pp2_s1_reg[27]/Q  -type DFF DFF
add mapped point pp2_s1[26]/q pp2_s1_reg[26]/Q  -type DFF DFF
add mapped point pp2_s1[25]/q pp2_s1_reg[25]/Q  -type DFF DFF
add mapped point pp2_s1[23]/q pp2_s1_reg[23]/Q  -type DFF DFF
add mapped point pp0_s1[39]/q pp0_s1_reg[39]/Q  -type DFF DFF
add mapped point pp2_s1[22]/q pp2_s1_reg[22]/Q  -type DFF DFF
add mapped point pp2_s1[20]/q pp2_s1_reg[20]/Q  -type DFF DFF
add mapped point pp2_s1[19]/q pp2_s1_reg[19]/Q  -type DFF DFF
add mapped point pp0_s1[38]/q pp0_s1_reg[38]/Q  -type DFF DFF
add mapped point pp2_s1[17]/q pp2_s1_reg[17]/Q  -type DFF DFF
add mapped point pp0_s1[37]/q pp0_s1_reg[37]/Q  -type DFF DFF
add mapped point pp2_s1[16]/q pp2_s1_reg[16]/Q  -type DFF DFF
add mapped point pp1_s1[36]/q pp1_s1_reg[36]/Q  -type DFF DFF
add mapped point pp0_s1[36]/q pp0_s1_reg[36]/Q  -type DFF DFF
add mapped point pp2_s1[14]/q pp2_s1_reg[14]/Q  -type DFF DFF
add mapped point pp0_s1[35]/q pp0_s1_reg[35]/Q  -type DFF DFF
add mapped point pp2_s1[12]/q pp2_s1_reg[12]/Q  -type DFF DFF
add mapped point pp2_s1[11]/q pp2_s1_reg[11]/Q  -type DFF DFF
add mapped point pp2_s1[10]/q pp2_s1_reg[10]/Q  -type DFF DFF
add mapped point pp2_s1[9]/q pp2_s1_reg[9]/Q  -type DFF DFF
add mapped point pp0_s1[33]/q pp0_s1_reg[33]/Q  -type DFF DFF
add mapped point pp3_s1[39]/q pp3_s1_reg[39]/Q  -type DFF DFF
add mapped point pp1_s1[37]/q pp1_s1_reg[37]/Q  -type DFF DFF
add mapped point pp0_s1[32]/q pp0_s1_reg[32]/Q  -type DFF DFF
add mapped point pp3_s1[37]/q pp3_s1_reg[37]/Q  -type DFF DFF
add mapped point pp0_s1[31]/q pp0_s1_reg[31]/Q  -type DFF DFF
add mapped point pp3_s1[36]/q pp3_s1_reg[36]/Q  -type DFF DFF
add mapped point pp3_s1[0]/q pp3_s1_reg[0]/Q  -type DFF DFF
add mapped point pp3_s1[1]/q pp3_s1_reg[1]/Q  -type DFF DFF
add mapped point pp3_s1[35]/q pp3_s1_reg[35]/Q  -type DFF DFF
add mapped point pp3_s1[4]/q pp3_s1_reg[4]/Q  -type DFF DFF
add mapped point pp0_s1[30]/q pp0_s1_reg[30]/Q  -type DFF DFF
add mapped point pp3_s1[34]/q pp3_s1_reg[34]/Q  -type DFF DFF
add mapped point pp3_s1[8]/q pp3_s1_reg[8]/Q  -type DFF DFF
add mapped point pp3_s1[9]/q pp3_s1_reg[9]/Q  -type DFF DFF
add mapped point pp3_s1[33]/q pp3_s1_reg[33]/Q  -type DFF DFF
add mapped point pp3_s1[12]/q pp3_s1_reg[12]/Q  -type DFF DFF
add mapped point pp0_s1[29]/q pp0_s1_reg[29]/Q  -type DFF DFF
add mapped point pp3_s1[32]/q pp3_s1_reg[32]/Q  -type DFF DFF
add mapped point pp0_s1[28]/q pp0_s1_reg[28]/Q  -type DFF DFF
add mapped point pp3_s1[30]/q pp3_s1_reg[30]/Q  -type DFF DFF
add mapped point pp3_s1[29]/q pp3_s1_reg[29]/Q  -type DFF DFF
add mapped point pp2_s1[31]/q pp2_s1_reg[31]/Q  -type DFF DFF
add mapped point pp3_s1[20]/q pp3_s1_reg[20]/Q  -type DFF DFF
add mapped point pp0_s1[27]/q pp0_s1_reg[27]/Q  -type DFF DFF
add mapped point pp3_s1[28]/q pp3_s1_reg[28]/Q  -type DFF DFF
add mapped point pp0_s1[26]/q pp0_s1_reg[26]/Q  -type DFF DFF
add mapped point pp3_s1[26]/q pp3_s1_reg[26]/Q  -type DFF DFF
add mapped point pp3_s1[25]/q pp3_s1_reg[25]/Q  -type DFF DFF
add mapped point pp3_s1[24]/q pp3_s1_reg[24]/Q  -type DFF DFF
add mapped point pp3_s1[23]/q pp3_s1_reg[23]/Q  -type DFF DFF
add mapped point pp0_s1[24]/q pp0_s1_reg[24]/Q  -type DFF DFF
add mapped point pp2_s1[30]/q pp2_s1_reg[30]/Q  -type DFF DFF
add mapped point pp2_s1[32]/q pp2_s1_reg[32]/Q  -type DFF DFF
add mapped point pp0_s1[22]/q pp0_s1_reg[22]/Q  -type DFF DFF
add mapped point pp0_s1[20]/q pp0_s1_reg[20]/Q  -type DFF DFF
add mapped point pp3_s1[14]/q pp3_s1_reg[14]/Q  -type DFF DFF
add mapped point pp3_s1[13]/q pp3_s1_reg[13]/Q  -type DFF DFF
add mapped point pp0_s1[18]/q pp0_s1_reg[18]/Q  -type DFF DFF
add mapped point pp3_s1[10]/q pp3_s1_reg[10]/Q  -type DFF DFF
add mapped point pp0_s1[17]/q pp0_s1_reg[17]/Q  -type DFF DFF
add mapped point pp3_s1[6]/q pp3_s1_reg[6]/Q  -type DFF DFF
add mapped point pp3_s1[5]/q pp3_s1_reg[5]/Q  -type DFF DFF
add mapped point pp0_s1[15]/q pp0_s1_reg[15]/Q  -type DFF DFF
add mapped point pp3_s1[2]/q pp3_s1_reg[2]/Q  -type DFF DFF
add mapped point pp0_s1[14]/q pp0_s1_reg[14]/Q  -type DFF DFF
add mapped point pp0_s1[12]/q pp0_s1_reg[12]/Q  -type DFF DFF
add mapped point pp1_s1[39]/q pp1_s1_reg[39]/Q  -type DFF DFF
add mapped point pp3_s1[18]/q pp3_s1_reg[18]/Q  -type DFF DFF
add mapped point pp0_s1[8]/q pp0_s1_reg[8]/Q  -type DFF DFF
add mapped point pp3_s1[16]/q pp3_s1_reg[16]/Q  -type DFF DFF
add mapped point pp0_s1[21]/q pp0_s1_reg[21]/Q  -type DFF DFF
add mapped point pp3_s1[15]/q pp3_s1_reg[15]/Q  -type DFF DFF
add mapped point pp1_s1[34]/q pp1_s1_reg[34]/Q  -type DFF DFF
add mapped point pp1_s1[33]/q pp1_s1_reg[33]/Q  -type DFF DFF
add mapped point pp1_s1[32]/q pp1_s1_reg[32]/Q  -type DFF DFF
add mapped point pp1_s1[31]/q pp1_s1_reg[31]/Q  -type DFF DFF
add mapped point pp1_s1[30]/q pp1_s1_reg[30]/Q  -type DFF DFF
add mapped point pp1_s1[29]/q pp1_s1_reg[29]/Q  -type DFF DFF
add mapped point pp0_s1[25]/q pp0_s1_reg[25]/Q  -type DFF DFF
add mapped point pp1_s1[27]/q pp1_s1_reg[27]/Q  -type DFF DFF
add mapped point pp1_s1[26]/q pp1_s1_reg[26]/Q  -type DFF DFF
add mapped point pp1_s1[25]/q pp1_s1_reg[25]/Q  -type DFF DFF
add mapped point pp1_s1[23]/q pp1_s1_reg[23]/Q  -type DFF DFF
add mapped point pp1_s1[22]/q pp1_s1_reg[22]/Q  -type DFF DFF
add mapped point pp1_s1[21]/q pp1_s1_reg[21]/Q  -type DFF DFF
add mapped point pp0_s1[9]/q pp0_s1_reg[9]/Q  -type DFF DFF
add mapped point pp1_s1[19]/q pp1_s1_reg[19]/Q  -type DFF DFF
add mapped point pp1_s1[18]/q pp1_s1_reg[18]/Q  -type DFF DFF
add mapped point pp1_s1[16]/q pp1_s1_reg[16]/Q  -type DFF DFF
add mapped point pp1_s1[15]/q pp1_s1_reg[15]/Q  -type DFF DFF
add mapped point pp1_s1[14]/q pp1_s1_reg[14]/Q  -type DFF DFF
add mapped point pp1_s1[20]/q pp1_s1_reg[20]/Q  -type DFF DFF
add mapped point pp1_s1[12]/q pp1_s1_reg[12]/Q  -type DFF DFF
add mapped point pp1_s1[11]/q pp1_s1_reg[11]/Q  -type DFF DFF
add mapped point pp1_s1[10]/q pp1_s1_reg[10]/Q  -type DFF DFF
add mapped point pp1_s1[8]/q pp1_s1_reg[8]/Q  -type DFF DFF
add mapped point pp1_s1[7]/q pp1_s1_reg[7]/Q  -type DFF DFF
add mapped point pp1_s1[6]/q pp1_s1_reg[6]/Q  -type DFF DFF
add mapped point pp1_s1[4]/q pp1_s1_reg[4]/Q  -type DFF DFF
add mapped point pp1_s1[3]/q pp1_s1_reg[3]/Q  -type DFF DFF
add mapped point pp1_s1[2]/q pp1_s1_reg[2]/Q  -type DFF DFF
add mapped point pp1_s1[0]/q pp1_s1_reg[0]/Q  -type DFF DFF
add mapped point pp2_s1[39]/q pp2_s1_reg[39]/Q  -type DFF DFF
add mapped point pp2_s1[38]/q pp2_s1_reg[38]/Q  -type DFF DFF
add mapped point pp2_s1[36]/q pp2_s1_reg[36]/Q  -type DFF DFF
add mapped point pp2_s1[35]/q pp2_s1_reg[35]/Q  -type DFF DFF
add mapped point pp2_s1[34]/q pp2_s1_reg[34]/Q  -type DFF DFF
add mapped point pp0_s1[23]/q pp0_s1_reg[23]/Q  -type DFF DFF
add mapped point pp0_s1[10]/q pp0_s1_reg[10]/Q  -type DFF DFF
add mapped point pp2_s1[33]/q pp2_s1_reg[33]/Q  -type DFF DFF
add mapped point pp0_s1[11]/q pp0_s1_reg[11]/Q  -type DFF DFF
add mapped point pp2_s1[37]/q pp2_s1_reg[37]/Q  -type DFF DFF
add mapped point pp1_s1[38]/q pp1_s1_reg[38]/Q  -type DFF DFF
add mapped point pp1_s1[1]/q pp1_s1_reg[1]/Q  -type DFF DFF
add mapped point pp0_s1[16]/q pp0_s1_reg[16]/Q  -type DFF DFF
add mapped point pp1_s1[5]/q pp1_s1_reg[5]/Q  -type DFF DFF
add mapped point pp0_s1[19]/q pp0_s1_reg[19]/Q  -type DFF DFF
add mapped point pp1_s1[9]/q pp1_s1_reg[9]/Q  -type DFF DFF
add mapped point pp3_s1[17]/q pp3_s1_reg[17]/Q  -type DFF DFF
add mapped point pp1_s1[13]/q pp1_s1_reg[13]/Q  -type DFF DFF
add mapped point pp3_s1[22]/q pp3_s1_reg[22]/Q  -type DFF DFF
add mapped point pp1_s1[17]/q pp1_s1_reg[17]/Q  -type DFF DFF
add mapped point valid_out/q valid_out_reg/Q  -type DFF DFF
add mapped point valid_s2/q valid_s2_reg/Q  -type DFF DFF
add mapped point valid_s1/q valid_s1_reg/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
