# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Fri Jun 05 09:53:52 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design mul32_pipeline

create_clock -name "clk" -period 4.0 -waveform {0.0 0.5} [get_ports clk]
set_clock_transition 0.1 [get_clocks clk]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports valid_in]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[31]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[30]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[29]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[28]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[27]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[26]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[25]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[24]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[23]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[22]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[21]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[20]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[19]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[18]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[17]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[16]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {a[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[31]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[30]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[29]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[28]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[27]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[26]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[25]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[24]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[23]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[22]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[21]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[20]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[19]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[18]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[17]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[16]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[15]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[14]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {b[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports valid_out]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[63]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[62]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[61]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[60]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[59]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[58]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[57]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[56]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[55]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[54]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[53]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[52]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[51]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[50]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[49]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[48]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[47]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[46]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[45]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[44]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[43]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[42]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[41]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[40]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[39]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[38]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[37]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[36]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[35]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[34]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[33]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[32]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[31]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[30]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[29]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[28]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[27]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[26]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[25]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[24]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[23]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[22]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[21]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[20]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[19]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[18]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[17]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[16]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[15]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[14]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.4 [get_ports {product[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.01 [get_ports clk]
set_clock_uncertainty -hold 0.01 [get_ports clk]
