
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun  4 2026 15:29:59 IST (Jun  4 2026 09:59:59 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, up_down, count);
  input clk, reset, up_down;
  output [3:0] count;
  wire clk, reset, up_down;
  wire [3:0] count;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_23;
  DFFRHQX1 \count_reg[3] (.RN (n_18), .CK (clk), .D (n_19), .Q
       (count[3]));
  OAI211X1 g1737__2398(.A0 (n_4), .A1 (n_10), .B0 (n_23), .C0 (n_16),
       .Y (n_19));
  DFFRHQX1 \count_reg[2] (.RN (n_18), .CK (clk), .D (n_17), .Q
       (count[2]));
  OAI21X1 g1738__5107(.A0 (count[2]), .A1 (n_13), .B0 (n_14), .Y
       (n_17));
  AOI31X1 g1740__6260(.A0 (up_down), .A1 (count[3]), .A2 (n_8), .B0
       (n_9), .Y (n_16));
  MXI2XL g1741__4319(.A (n_11), .B (up_down), .S0 (n_7), .Y (n_15));
  NAND2XL g1739__8428(.A (count[2]), .B (n_13), .Y (n_14));
  NOR3X1 g1743__6783(.A (count[3]), .B (n_11), .C (n_8), .Y (n_9));
  AOI33XL g1744__3680(.A0 (n_11), .A1 (n_6), .A2 (n_5), .B0 (count[1]),
       .B1 (up_down), .B2 (count[0]), .Y (n_13));
  OAI22X1 g1747__1617(.A0 (count[1]), .A1 (count[0]), .B0 (n_6), .B1
       (n_5), .Y (n_7));
  NAND2XL g1749__2802(.A (count[3]), .B (n_11), .Y (n_4));
  NAND3X1 g1746__1705(.A (count[2]), .B (count[1]), .C (count[0]), .Y
       (n_8));
  NOR3X1 g1745__5122(.A (count[2]), .B (count[1]), .C (count[0]), .Y
       (n_10));
  INVXL g1750(.A (reset), .Y (n_18));
  CLKINVX2 g1757(.A (up_down), .Y (n_11));
  DFFRX1 \count_reg[1] (.RN (n_18), .CK (clk), .D (n_15), .Q
       (count[1]), .QN (n_6));
  DFFRX1 \count_reg[0] (.RN (n_18), .CK (clk), .D (n_5), .Q (count[0]),
       .QN (n_5));
  NAND3BX1 g2(.AN (count[3]), .B (n_11), .C (n_10), .Y (n_23));
endmodule

